name: snapping_page_scroll
description: A plugin that allows you to make a pageView that scrolls a certain number of pages based on the scroll velocity, and then snaps to the nearest page.
version: 3.1.0
homepage: https://www.solidred.se
repository: https://github.com/solidredcompany/snapping_page_scroll

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
